<a href="https://colab.research.google.com/github/aysenuruyar-rgb/DSA210-Proj/blob/main/notebook/feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("final_dataset.csv", index_col=0)
df.index = pd.to_datetime(df.index)

df["dam_lag_1"] = df["GENERAL_DAM_OCCUPANCY_RATE"].shift(1)
df["dam_lag_3"] = df["GENERAL_DAM_OCCUPANCY_RATE"].shift(3)

df["rain_lag_1"] = df["precipitation_sum (mm)"].shift(1)
df["rain_lag_3"] = df["precipitation_sum (mm)"].shift(3)
df["snow_lag_1"] = df["snowfall_sum (cm)"].shift(1)
df["temp_lag_1"] = df["temperature_2m_mean (°C)"].shift(1)
df.head()

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm),dam_lag_1,dam_lag_3,rain_lag_1,rain_lag_3,snow_lag_1,temp_lag_1
2005-01-31,46.650000,405.258065,126.2,7.006452,125.6,0.77,NaN,NaN,NaN,NaN,NaN,NaN
2005-02-28,72.679286,631.285714,108.5,5.996429,87.7,14.91,46.650000,NaN,126.2,NaN,0.77,7.006452
2005-03-31,92.837097,806.419355,66.8,7.090323,56.7,7.28,72.679286,NaN,108.5,NaN,14.91,5.996429
2005-04-30,92.331667,802.100000,36.1,11.813333,36.1,0.00,92.837097,46.650000,66.8,126.2,7.28,7.090323
2005-05-31,87.719677,762.032258,12.3,16.148387,12.3,0.00,92.331667,72.679286,36.1,108.5,0.00,11.813333

In [4]:
df["rain_3m_avg"] = df["precipitation_sum (mm)"].rolling(3).mean()
df["temp_3m_avg"] = df["temperature_2m_mean (°C)"].rolling(3).mean()
df["dam_3m_avg"] = df["GENERAL_DAM_OCCUPANCY_RATE"].rolling(3).mean()

df["rain_snow_total"] = df["precipitation_sum (mm)"] + df["snowfall_sum (cm)"]

df["month"] = df.index.month
df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

threshold = df["precipitation_sum (mm)"].median()
df["is_rainy"] = (df["precipitation_sum (mm)"] > threshold).astype(int)

df.head()

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm),dam_lag_1,dam_lag_3,rain_lag_1,rain_lag_3,snow_lag_1,temp_lag_1,rain_3m_avg,temp_3m_avg,dam_3m_avg,rain_snow_total,month,month_sin,month_cos,is_rainy
2005-01-31,46.650000,405.258065,126.2,7.006452,125.6,0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126.97,1,0.500000,8.660254e-01,1
2005-02-28,72.679286,631.285714,108.5,5.996429,87.7,14.91,46.650000,NaN,126.2,NaN,0.77,7.006452,NaN,NaN,NaN,123.41,2,0.866025,5.000000e-01,1
2005-03-31,92.837097,806.419355,66.8,7.090323,56.7,7.28,72.679286,NaN,108.5,NaN,14.91,5.996429,100.500000,6.697734,70.722127,74.08,3,1.000000,6.123234e-17,1
2005-04-30,92.331667,802.100000,36.1,11.813333,36.1,0.00,92.837097,46.650000,66.8,126.2,7.28,7.090323,70.466667,8.300028,85.949350,36.10,4,0.866025,-5.000000e-01,0
2005-05-31,87.719677,762.032258,12.3,16.148387,12.3,0.00,92.331667,72.679286,36.1,108.5,0.00,11.813333,38.400000,11.684014,90.962814,12.30,5,0.500000,-8.660254e-01,0

In [5]:
df = df.dropna()
df.head()

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm),dam_lag_1,dam_lag_3,rain_lag_1,rain_lag_3,snow_lag_1,temp_lag_1,rain_3m_avg,temp_3m_avg,dam_3m_avg,rain_snow_total,month,month_sin,month_cos,is_rainy
2005-04-30,92.331667,802.100000,36.1,11.813333,36.1,0.0,92.837097,46.650000,66.8,126.2,7.28,7.090323,70.466667,8.300028,85.949350,36.1,4,8.660254e-01,-0.500000,0
2005-05-31,87.719677,762.032258,12.3,16.148387,12.3,0.0,92.331667,72.679286,36.1,108.5,0.00,11.813333,38.400000,11.684014,90.962814,12.3,5,5.000000e-01,-0.866025,0
2005-06-30,83.309333,723.666667,8.2,20.243333,8.2,0.0,87.719677,92.837097,12.3,66.8,0.00,16.148387,18.866667,16.068351,87.786892,8.2,6,1.224647e-16,-1.000000,0
2005-07-31,76.624516,665.741935,71.9,23.506452,71.9,0.0,83.309333,92.331667,8.2,36.1,0.00,20.243333,30.800000,19.966057,82.551176,71.9,7,-5.000000e-01,-0.866025,1
2005-08-31,68.293871,593.129032,9.3,24.680645,9.3,0.0,76.624516,87.719677,71.9,12.3,0.00,23.506452,29.800000,22.810143,76.075907,9.3,8,-8.660254e-01,-0.500000,0

In [6]:
df.columns

Index(['GENERAL_DAM_OCCUPANCY_RATE', 'GENERAL_DAM_RESERVED_WATER',
       'precipitation_sum (mm)', 'temperature_2m_mean (°C)', 'rain_sum (mm)',
       'snowfall_sum (cm)', 'dam_lag_1', 'dam_lag_3', 'rain_lag_1',
       'rain_lag_3', 'snow_lag_1', 'temp_lag_1', 'rain_3m_avg', 'temp_3m_avg',
       'dam_3m_avg', 'rain_snow_total', 'month', 'month_sin', 'month_cos',
       'is_rainy'],
      dtype='object')

In [7]:
df.to_csv("featured_dataset.csv")