<a href="https://colab.research.google.com/github/aysenuruyar-rgb/DSA210-Proj/blob/main/analysis/01_data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
general_dam = pd.read_csv("dam_occupancy.csv")
individual_dam = pd.read_excel("istanbul-dams-daily-occupancy-rates.xlsx")
weather = pd.read_csv("weather_data.csv", skiprows=2)

In [7]:
print("GENERAL DAM DATA")
display(general_dam.head())

print("INDIVIDUAL DAM DATA")
display(individual_dam.head())

print("WEATHER DATA")
display(weather.head())

GENERAL DAM DATA

         DATE  GENERAL_DAM_OCCUPANCY_RATE  GENERAL_DAM_RESERVED_WATER
0  2005-01-01                       44.62                         388
1  2005-01-02                       44.62                         388
2  2005-01-03                       44.47                         386
3  2005-01-04                       44.42                         386
4  2005-01-05                       44.35                         385

INDIVIDUAL DAM DATA

,Tarih,Ömerli,Darlık,Elmalı,Terkos,Alibey,Büyükçekmece,Sazlıdere,Kazandere,Pabuçdere,Istrancalar
0,2000-10-23 00:00:00,0.652551,0.750151,0.789792,0.708568,0.0,0.521442,0.505489,0.057499,0.068553,0.110953
1,2000-10-24 00:00:00,0.659731,0.773031,0.817187,0.710344,0.0,0.521442,0.506952,0.057499,0.069092,0.077226
2,2000-10-25 00:00:00,0.663327,0.787929,0.826667,0.708568,0.0,0.519666,0.506952,0.057499,0.069361,0.105593
3,2000-10-26 00:00:00,0.662608,0.793250,0.828125,0.706792,0.0,0.517889,0.506952,0.057499,0.069624,0.114171
4,2000-10-27 00:00:00,0.660450,0.795911,0.828125,0.706792,0.0,0.516113,0.505489,0.057499,0.066667,0.114017

WEATHER DATA

,time,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm)
0,2000-01-27,0.0,-3.0,0.0,0.0
1,2000-01-28,0.0,1.6,0.0,0.0
2,2000-01-29,0.0,2.2,0.0,0.0
3,2000-01-30,0.0,6.7,0.0,0.0
4,2000-01-31,0.0,8.0,0.0,0.0

In [8]:
general_dam["DATE"] = pd.to_datetime(general_dam["DATE"])
general_dam = general_dam.set_index("DATE")

individual_dam["Tarih"] = pd.to_datetime(individual_dam["Tarih"])
individual_dam = individual_dam.set_index("Tarih")

weather["time"] = pd.to_datetime(weather["time"])
weather = weather.set_index("time")

print(general_dam.index)
print(individual_dam.index)
print(weather.index)

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10',
               ...
               '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01',
               '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05',
               '2021-04-06', '2021-04-07'],
              dtype='datetime64[ns]', name='DATE', length=5941, freq=None)
DatetimeIndex(['2000-10-23', '2000-10-24', '2000-10-25', '2000-10-26',
               '2000-10-27', '2000-10-28', '2000-10-29', '2000-10-30',
               '2000-10-31', '2000-11-01',
               ...
               '2024-02-10', '2024-02-11', '2024-02-12', '2024-02-13',
               '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-17',
               '2024-02-18', '2024-02-19'],
              dtype='datetime64[ns]', name='Tarih', length=8520, freq=None)
DatetimeIndex(['2000-01-27', '2000-01-28', '2000-01-29', '2000-01-30',
               '2000-01-31', '2000-02-01', '2000-02-02', '2000-02-03',
               '2000-02-04', '2000-02-05',
               ...
               '2026-04-02', '2026-04-03', '2026-04-04', '2026-04-05',
               '2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09',
               '2026-04-10', '2026-04-11'],
              dtype='datetime64[ns]', name='time', length=9572, freq=None)

In [11]:
dam_rate_monthly = general_dam["GENERAL_DAM_OCCUPANCY_RATE"].resample("ME").mean()
dam_water_monthly = general_dam["GENERAL_DAM_RESERVED_WATER"].resample("ME").mean()

dam_monthly = pd.concat([dam_rate_monthly, dam_water_monthly], axis=1)

display(dam_monthly.head())

rain_monthly = weather["precipitation_sum (mm)"].resample("ME").sum()
temp_monthly = weather["temperature_2m_mean (°C)"].resample("ME").mean()
rain_only_monthly = weather["rain_sum (mm)"].resample("ME").sum()
snow_monthly = weather["snowfall_sum (cm)"].resample("ME").sum()

weather_monthly = pd.concat([rain_monthly, temp_monthly, rain_only_monthly, snow_monthly],axis=1)

display(weather_monthly.head())

omerli_monthly = individual_dam["Ömerli"].resample("ME").mean()
darlik_monthly = individual_dam["Darlık"].resample("ME").mean()
elmali_monthly = individual_dam["Elmalı"].resample("ME").mean()
terkos_monthly = individual_dam["Terkos"].resample("ME").mean()
alibey_monthly = individual_dam["Alibey"].resample("ME").mean()
buyukcekmece_monthly = individual_dam["Büyükçekmece"].resample("ME").mean()
sazlidere_monthly = individual_dam["Sazlıdere"].resample("ME").mean()
kazandere_monthly = individual_dam["Kazandere"].resample("ME").mean()
pabucdere_monthly = individual_dam["Pabuçdere"].resample("ME").mean()
istrancalar_monthly = individual_dam["Istrancalar"].resample("ME").mean()

individual_monthly = pd.concat([
    omerli_monthly,
    darlik_monthly,
    elmali_monthly,
    terkos_monthly,
    alibey_monthly,
    buyukcekmece_monthly,
    sazlidere_monthly,
    kazandere_monthly,
    pabucdere_monthly,
    istrancalar_monthly
], axis=1)


display(individual_monthly.head())

            GENERAL_DAM_OCCUPANCY_RATE  GENERAL_DAM_RESERVED_WATER
DATE
2005-01-31                   46.650000                  405.258065
2005-02-28                   72.679286                  631.285714
2005-03-31                   92.837097                  806.419355
2005-04-30                   92.331667                  802.100000
2005-05-31                   87.719677                  762.032258

,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm)
time,,,,
2000-01-31,0.0,3.100000,0.0,0.00
2000-02-29,65.2,5.962069,65.0,0.14
2000-03-31,85.1,7.283871,69.9,10.64
2000-04-30,84.5,13.186667,84.5,0.00
2000-05-31,68.9,15.803226,68.9,0.00

,Ömerli,Darlık,Elmalı,Terkos,Alibey,Büyükçekmece,Sazlıdere,Kazandere,Pabuçdere,Istrancalar
Tarih,,,,,,,,,,
2000-10-31,0.657896,0.788580,0.822002,0.703449,0.000000,0.515915,0.505604,0.057499,0.067774,0.116090
2000-11-30,0.624156,0.775939,0.803226,0.636836,0.025877,0.488521,0.496378,0.075501,0.066667,0.195258
2000-12-31,0.664064,0.771932,0.838821,0.558814,0.142458,0.464027,0.493079,0.061342,0.070104,0.145818
2001-01-31,0.685713,0.779038,0.868874,0.570685,0.335908,0.483509,0.545932,0.084048,0.122185,0.401097
2001-02-28,0.734014,0.830972,0.897474,0.760497,0.542564,0.582226,0.636580,0.277358,0.330158,0.716967

In [12]:
final_data = pd.concat([dam_monthly, weather_monthly], axis=1)

display(final_data.head())
print(final_data.columns)

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm)
2000-01-31,NaN,NaN,0.0,3.100000,0.0,0.00
2000-02-29,NaN,NaN,65.2,5.962069,65.0,0.14
2000-03-31,NaN,NaN,85.1,7.283871,69.9,10.64
2000-04-30,NaN,NaN,84.5,13.186667,84.5,0.00
2000-05-31,NaN,NaN,68.9,15.803226,68.9,0.00

Index(['GENERAL_DAM_OCCUPANCY_RATE', 'GENERAL_DAM_RESERVED_WATER',
       'precipitation_sum (mm)', 'temperature_2m_mean (°C)', 'rain_sum (mm)',
       'snowfall_sum (cm)'],
      dtype='object')

In [13]:
final_data = final_data.dropna()

display(final_data.head())
display(final_data.tail())
print(final_data.shape)

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm)
2005-01-31,46.650000,405.258065,126.2,7.006452,125.6,0.77
2005-02-28,72.679286,631.285714,108.5,5.996429,87.7,14.91
2005-03-31,92.837097,806.419355,66.8,7.090323,56.7,7.28
2005-04-30,92.331667,802.100000,36.1,11.813333,36.1,0.00
2005-05-31,87.719677,762.032258,12.3,16.148387,12.3,0.00

,GENERAL_DAM_OCCUPANCY_RATE,GENERAL_DAM_RESERVED_WATER,precipitation_sum (mm),temperature_2m_mean (°C),rain_sum (mm),snowfall_sum (cm)
2020-12-31,22.123226,191.677419,37.0,10.561290,37.0,0.00
2021-01-31,27.173750,235.531250,149.5,8.087097,133.9,10.99
2021-02-28,47.902857,415.607143,59.6,7.121429,33.0,18.62
2021-03-31,63.737419,553.225806,95.5,6.832258,95.4,0.07
2021-04-30,74.452857,646.142857,68.1,10.876667,68.1,0.00

(196, 6)

In [14]:
print(final_data.isnull().sum())

GENERAL_DAM_OCCUPANCY_RATE    0
GENERAL_DAM_RESERVED_WATER    0
precipitation_sum (mm)        0
temperature_2m_mean (°C)      0
rain_sum (mm)                 0
snowfall_sum (cm)             0
dtype: int64

In [15]:
final_data.to_csv("final_dataset.csv")